services:
    # default configuration for services in *this* file

    Rustam\MBundle\Routing\MLoader:
        tags: [routing.loader]
        arguments: ['@service_container']

    Rustam\MBundle\EventListener\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }
